<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.18" />
    <PackageReference Include="ModelContextProtocol" Version="1.4.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
    <Content Remove="Tests\**\*" />
    <EmbeddedResource Remove="Tests\**\*" />
    <None Remove="Tests\**\*" />
    <Content Include="Infrastructure\PostgreSql\Migrations\*.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
